version: '3.8'

services:
  # SERVICIO 1: Base de Datos MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongo_lab_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    volumes:
      - mongo_data:/data/db

  # SERVICIO 2: Panel Visual (Mongo Express) - http://localhost:8081
  mongo-express:
    image: mongo-express
    container_name: mongo_gui
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin123@mongodb:27017/
    depends_on:
      - mongodb

  # SERVICIO 3: Backend Node.js
  backend:
    build: ./Backend
    container_name: backend_lab_api
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    environment:
      - PORT=5000
      # CONEXIÃ“N DOCKER: Usa 'mongodb' en lugar de 'localhost'
      - MONGO_URI=mongodb://admin:admin123@mongodb:27017/gestion_laboratorios?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - ./Backend:/app
      - /app/node_modules

  # SERVICIO 4: Frontend (Vite + Nginx)
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        # Se inyecta en build de Vite
        VITE_API_URL: /api
    container_name: frontend_lab_web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
