version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_lab_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_gui
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin123@mongodb:27017/
    depends_on:
      - mongodb

  backend:
    build: ./Backend
    container_name: backend_lab_api
    restart: always
    ports:
<<<<<<< HEAD
      - "5000:5000"
    env_file:
      - ./Backend/.env  # ← ESTA ES LA CLAVE
=======
      - "5000:5000"  
    env_file:
      - ./Backend/.env # <--- CORREGIDO: Mapea el puerto 5000 real
    environment:
      - PORT=5000
      # CONEXIÓN DOCKER: Usa 'mongodb' en lugar de 'localhost'
      - MONGO_URI=mongodb://admin:admin123@mongodb:27017/gestion_laboratorios?authSource=admin
      # Agrega aquí tus credenciales de Firebase si las usas por variables de entorno
      # - FIREBASE_PROJECT_ID=...
>>>>>>> rescue-avances
    depends_on:
      - mongodb
    volumes:
      - ./Backend:/app
      - /app/node_modules

volumes:
  mongo_data:
